pipelines:
  hyaku:
    group: delivery
    environment_variables:
        PROJECT_GROUP: "sre"
        PUBLISH_AWS: "true"
    materials:
      project-code:
        git: https://github.com/t00lmaker/apiStransTHE.git
        branch: master
        destination: project
      scripts-code:
        git: https://github.com/t00lmaker/gocd-scripts.git
        branch: master
        blacklist:
          - '**/*'
        destination: scripts
    stages:
      - build:
          clean_workspace: true
          jobs:
            maven:
              resources:
                - build
              artifacts:
                - build:
                    source: project/target
              tasks:
                - exec:
                    command: /usr/bin/mvn
                    arguments:
                      - install
                      - -f
                      - project/